### ISSUE TITLE
Problem in running sgx features on guest.

### ISSUE THREAD

**Issue by ideal8901** [intel/qemu-sgx#1]
Hi,

I have problem in running sgx applications on guest.  It doesn't execute further, after entering sgx_ecall in sdk.  

My logs are below. 

**Guest machine** 

sgx3@sgx3-Standard-PC-i440FX-PIIX-1996:~/NestedSGX/benchmarks/Demo$ dmesg | grep sgx
[    6.286928] systemd[1]: Set hostname to <sgx3-Standard-PC-i440FX-PIIX-1996>.
[    7.953436] isgx: loading out-of-tree module taints kernel.
[    7.953456] isgx: module verification failed: signature and/or required key missing - tainting kernel
[    7.954087] intel_sgx: Intel SGX Driver v0.10

**Host machine**

KVM
sgx3@sgx3-desktop:~/NSGX/kvm-sgx$ uname -r
4.14.0+
sgx3@sgx3-desktop:~/NSGX/kvm-sgx$ dmesg | grep sgx
[    0.000000] Linux version 4.14.0+ (sgx3@sgx3-desktop) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)) #1 SMP Thu Mar 15 14:58:29 KST 2018
[    0.084411] intel_sgx: EPC bank 0x70200000-0x75f80000
[    6.037216] systemd[1]: Set hostname to <sgx3-desktop>.
[    8.902801] intel_sgx: the CPU is missing launch control

QEMU

1)
sudo qemu-system-x86_64 --enable-kvm -cpu host -machine epc=16384 -m 16384 -smp 4  -hda vm.img -drive media=cdrom,file=./ubuntu-16.04.4-desktop-amd64.iso -net user,hostfwd=tcp::2222-:22 -net nic
>> qemu-system-x86_64: Property '.epc' not found

2)
sudo qemu-system-x86_64 --enable-kvm -cpu host -machine epc=16384 -m 16384 -smp 4  -hda vm.img -drive media=cdrom,file=./ubuntu-16.04.4-desktop-amd64.iso -net user,hostfwd=tcp::2222-:22 -net nic
>> qemu-system-x86_64: Property '.epc' not found

Since 1), 2) So, currently I am using command below.

3) 
sudo qemu-system-x86_64 --enable-kvm -cpu host -sgx epc=32M,le_wr -m 16384 -smp 4  -hda vm.img -drive media=cdrom,file=./ubuntu-16.04.4-desktop-amd64.iso -net user,hostfwd=tcp::2222-:22 -net nic

Generate SSDT for EPC: base 0xbdf00000, size 0x2100000
Generate SSDT for EPC: base 0xbdf00000, size 0x2100000

**Comment by sean-jc** [comment]
It looks like you're using a Qemu binary built from the old repository, which is no longer supported, e.g. `-sgx epc=...` was the previous method for specifying EPC.  The old Qemu is not compatible with the new kernel/KVM (and vice versa), please update and rebuild Qemu.

**Comment by ideal8901** [comment]
But I think I have already the newest version. Did I use wrong command? 
To build qemu-sgx , I used command below. 

mkdir build
cd build
sudo ../configure --target-list="x86_64-softmmu" --prefix=/usr --disable-xen --enable-sdl
cd ../
make 

sgx3@sgx3-desktop:~/NSGX/qemu-sgx$ git log
commit d1a8bd5b5312ea82cd71fbf62564e24763295e9f
Author: Sean Christopherson <sean.j.christopherson@intel.com>
Date:   Wed Mar 7 13:36:25 2018 -0800

    Qemu: add README.md for SGX repo (WIP)
    
    Signed-off-by: Sean Christopherson <sean.j.christopherson@intel.com>

sgx3@sgx3-desktop:~/NSGX/qemu-sgx$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

**Comment by ideal8901** [comment]
After I remove qemu binary manually,  and re install qemu-sgx, everything works fine. 

Thank you!
