### ISSUE TITLE
memory-backend-epc requires root?

### ISSUE THREAD

**Issue by jmechalas** [intel/qemu-sgx#4]
I was unable to get qemu 3.1.0 to start a VM with `-object memory-backend-epc,...` unless I ran qemu directly as root. Running virsh as a regular user to try and start the vm produced the error:
```
ealloc: invalid object type: memory-backend-epc
```
Does this sound right?

**Comment by sean-jc** [comment]
Yep.  Creating */dev/sgx_virt* with root permissions is intentional.  You can do e.g. `chmod 0666 /dev/sgx_virt` to expose EPC to all users.

**Comment by jmechalas** [comment]
Or 660 to a group allowed to use VMs. Or maybe there's a wall to get this to work as is using polkit. I'll think this over. I want the smoothest way to integrate this with libvirt without making everything wide open permissions-wise.

**Comment by jmechalas** [comment]
Adjusting permissions on the device didn't help with libvirt. Oddly enough I can't launch that way as root, either, so I suspect polkit _is_ the culprit. ANyway, this works if you run it from the command line directly so closing this out.
