### ISSUE TITLE
Can't run VM's with epc via libvirt

### ISSUE THREAD

**Issue by jmechalas** [intel/qemu-sgx#5]
Filing a new issue on this as I have narrowed down what I think is the cause here. I can execute QEMU vm's with sgx support via the command line, but not through the libvirt interface. Using libvirt results in the following failure:

```
$ virsh start Test
error: Failed to start domain Test
error: internal error: process exited while connecting to monitor: 2019-03-09T16:59:57.901776Z qemu-system-x86_64: -object memory-backend-epc,id=mem1,size=8M,prealloc: invalid object type: memory-backend-epc
```

I can take the command line that libvirt is executing from the logs in /var/log/libvirt, remove the libvirt-specific options, and then execute that resulting command as root and successfully run a VM.

libvirt wants to open a connection to kvm-spice, and that execve(2) includes the `-object memory-backend-epc` argument. From strace on libvirtd:

```
08:59:57.870626 execve("/usr/bin/kvm-spice", ["/usr/bin/kvm-spice", "-name", "guest=Test,debug-threads=on", "-S", "-object", "secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-24-Test/master-key.aes", "-machine", "pc-i440fx-3.1,accel=kvm,usb=off,dump-guest-core=off", "-cpu", "Skylake-Client-IBRS,ss=on,vmx=on,hypervisor=on,tsc_adjust=on,clflushopt=on,ssbd=on,xsaves=on,pdpe1gb=on", "-m", "2048", "-realtime", "mlock=off", "-smp", "1,sockets=1,cores=1,threads=1", "-uuid", "3d102957-3d04-4f5f-8c2a-06f9c4d6ca32", "-display", "none", "-no-user-config", "-nodefaults", "-chardev", "socket,id=charmonitor,path=/var/lib/libvirt/qemu/domain-24-Test/monitor.sock,server,nowait", "-mon", "chardev=charmonitor,id=monitor,mode=control", "-rtc", "base=utc", "-no-shutdown", "-boot", "strict=on", "-device", "piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2", "-drive", "file=/var/lib/libvirt/images/Test.qcow2,format=qcow2,if=none,id=drive-virtio-disk0", "-device", "virtio-blk-pci,scsi=off,bus=pci.0,addr=0x5,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1", "-device", "virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x4", "-cpu", "host,+sgx,+sgxlc", "-object", "memory-backend-epc,id=mem1,size=8M,prealloc", "-sgx-epc", "id=epc1,memdev=mem1", "-msg", "timestamp=on"], 0x7fec84135520 /* 3 vars */) = 0
```

On possibility is that kvm-spice is bombing out on this argument.

Another option is that, later on in this same strace, a failure occurs while opening `/dev/sgx_virt`:

```
08:59:57.897016 openat(AT_FDCWD, "/dev/sgx_virt", O_RDWR) = -1 EPERM (Operation not permitted)
```

The error is EPERM, not EACCESS, so this isn't a permissions issue.

**Comment by jmechalas** [comment]
Since /usr/bin/kvm-spice is just a sumlink to /usr/bin/kvm, this may be a kvm-sgx issue and not a qmeu-sgx one but I figured I'd start here since I am not sure exactly who is responsible.

**Comment by jmechalas** [comment]
OK. I am pretty sure it's something about qemu+libvirt interaction and not kvm as I have strace output where libvirt isn't running kvm-spice at all, and just executing qemu.

I do think the error when opening `/dev/sgx_virt` is the culprit, or at least a symptom of the problem. If I run qemu directly as root I get this from strace:

```
10:40:24.304823 readlink("/proc/self/exe", "/usr/local/bin/qemu-system-x86_6"...
, 4095) = 33
10:40:24.304931 brk(0x564ff95d8000)     = 0x564ff95d8000
10:40:24.305001 memfd_create("test", 0) = 3
10:40:24.305022 close(3)                = 0
10:40:24.305040 openat(AT_FDCWD, "/dev/sgx_virt", O_RDWR) = 3
10:40:24.305061 close(3)                = 0
10:40:24.305197 brk(0x564ff95f9000)     = 0x564ff95f9000
...
10:40:24.307332 getuid()                = 0
```

If I try to launch via libvirt (using `virsh start`), strace shows me this:

```
10:39:32.589972 setregid(64055, 64055)  = 0
10:39:32.589988 setgroups(2, [0, 64055]) = 0
10:39:32.590007 setreuid(0, 0)          = 0
...
10:39:32.598400 execve("/usr/local/bin/qemu-system-x86_64", [...], 0x7fec7c2d09c0 /* 3 vars */) = 0
...
10:39:32.623834 readlink("/proc/self/exe", "/usr/local/bin/qemu-system-x86_64", 
4095) = 33
10:39:32.624083 brk(0x5576e8506000)     = 0x5576e8506000
10:39:32.624774 memfd_create("test", 0) = 3
10:39:32.624807 close(3)                = 0
10:39:32.624900 openat(AT_FDCWD, "/dev/sgx_virt", O_RDWR) = -1 EPERM (Operation not permitted)
10:39:32.625060 brk(0x5576e8527000)     = 0x5576e8527000
```
Real and effective uid's are 0 at this point, though the permissions on /dev/sgx_virt don't seem to matter (even if I `chmod og+rw /dev/sgx_virt` this fails). And the error is EPERM which shouldn't be permissions-related, anyway. I would expect to see EACCESS if it was.

**Comment by sean-jc** [comment]
Isn't `/usr/bin/kvm/` a symlink to a Qemu binary, e.g. `qemu-system-x86_64`?

Regardless, best guess is that libvirt is blocking access to `/dev/sgx_virt` via AppArmor or SELinux.  Assuming you're running a MAC, maybe try disabling it as a first step to see if that changes anything?

**Comment by jmechalas** [comment]
No SELinux and no apparmor here. But now it's working smoothly after a reboot so I am at a loss. :(

I'll go ahead and close this out.

**Comment by kaiokassiano** [comment]
@jmechalas Do you remember anything else you tried to get it working? I'm running into the same error here `qemu-system-x86_64:` -object memory-backend-epc,id=mem1,size=8M,prealloc: invalid object type: memory-backend-epc`. I got no luck with the reboot.

**Comment by sean-jc** [comment]
Are you able to run Qemu directly?

**Comment by kaiokassiano** [comment]
@sean-jc Yes. No errors are shown when running the example command:

`qemu-system-x86_64 -nographic -enable-kvm -cpu host,+sgx -object memory-backend-epc,id=mem1,size=8M,prealloc -sgx-epc id=epc1,memdev=mem1`

**Comment by jmechalas** [comment]
See [Virtualizing Intel® Software Guard Extensions with KVM and QEMU](https://software.intel.com/en-us/articles/virtualizing-intel-software-guard-extensions-with-kvm-and-qemu).

Libvirt’s security settings are preventing access to /dev/sgx_virt. Check the following:

1. /dev/sgx_virt should be in the cgroup_device_acl list in qemu.conf.
2. QEMU should be configured to run as uid 0 in qemu.conf.
3. Either disable your MAC or create an exception or profile to allow access to /dev/sgx_virt.

**Comment by kaiokmo** [comment]
Thanks @jmechalas. Somehow I missed those on the documentation. It's working now.
