### ISSUE TITLE
Error while running 'make' command

### ISSUE THREAD

**Issue by gokhalesushant65** [intel/qemu-sgx#6]
This is my OS info:

> dell@dell-OptiPlex-7050:~/mtech/qemu-sgx/build$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

I am trying to apply the patch to qemu for virtualizing sgx from the tag sgx-v3.0.0-r2 .
Getting the following error after firing 'make' command:
[qemuSGX_make_error.txt](https://github.com/intel/qemu-sgx/files/3039953/qemuSGX_make_error.txt)

The same error occurs with the latest tag (i.e. sgx-v3.1.0-r1).

**Note**: In ubuntu 18.04, this is running completely fine.

**Comment by sean-jc** [comment]
Does adding `#include "qemu/typedefs.h"` to _include/sysemu/hostmem.h_ resolve the build error?

**Comment by gokhalesushant65** [comment]
No, it didn't resolve the error.

**Comment by gokhalesushant65** [comment]
Have started getting the same error for ubuntu 18.04 for the tag sgx-v3.0.0-r2

**Comment by sean-jc** [comment]
That sounds like an issue in your build environment and/or config.  sgx-v3.0.0-r2 doesn't implement EPC as a memory backend, i.e. shouldn't touch hostmem.h whatsoever.  Can you reproduce the error from a clean build directory?

**Comment by gokhalesushant65** [comment]
For ubuntu 18.04:
The 'make'  command goes smoothly. I get that error after trying  'make install' .

So, I tried with sgx 3.1.0-r1 with fresh environment. But I get the same error while doing 'make install'

For ubuntu 16.04:
The error occurs during the 'make' command

**Comment by sean-jc** [comment]
Please attach your `config.status`, I'll try to reproduce.

**Comment by gokhalesushant65** [comment]
Attaching as 'config.txt' as  uploading of file with '.status' is unsupported:
[config.txt](https://github.com/intel/qemu-sgx/files/3062301/config.txt)

**Comment by zombull** [comment]
Ah, so I missed it before but you're compiling all flavors of Qemu.  In this case compilation is failing on the `i386-linux-user` target, which is a bug, but it can be easily avoided.  SGX is only supported on 64-bit kernels, so the only useful target is `x86_64-softmmu`.  Building only `x86_64-softmmu` will also save you a significant chunk of compilation time, e.g.:

`exec '../configure' '--target-list=x86_64-softmmu' "$@"`

As for the bug, I'll opportunistically fix it on the next release.

**Comment by gokhalesushant65** [comment]
could compile successfully with following command:

> ../configure --target-list=x86_64-softmmu

Now, when I try to start with the virtual machine with 'epc' option, it gives me the following error:

> dell@dell-OptiPlex-7050:~$ sudo qemu-system-x86_64 -enable-kvm -machine epc=40M -machine epc-below-4g=auto -m 8G -cpu host   ~/qemu_images/ubuntu_18_04.qcow2  -vga qxl
[sudo] password for dell: 
qemu-system-x86_64: Property '.epc' not found

What should be done?

**Comment by sean-jc** [comment]
The most recent Qemu build implements EPC as a memory backend.   See the README for details on how to enable EPC with the new command line options.
