### ISSUE TITLE
AES related Error

### ISSUE THREAD

**Issue by antonionehme** [intel/qemu-sgx#9]
Hi;

I am trying to compile this code using mingw64 on windows 10; I followed the steps n [](https://wiki.qemu.org/Hosts/W32#Native_builds_with_MSYS2). I encountered the errors below.
![image](https://user-images.githubusercontent.com/11300985/85045395-d1b11980-b186-11ea-920b-76adb92848ae.png).
I tried updating the aes.h file (by copying the files in qemu-sgx\include\crypto to C:/Users/ID126219/asenv/msys2/mingw64/include/nettle/) but that did not work.
Any hint would be appreciated.

Many thanks.

**Comment by sean-jc** [comment]
This is not an SGX specific issue so I won't be of much help with the error itself.  You can workaround the fatal error by running configure with `--disable-werror`.
